# 配置中心
spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: qx-config-eureka-client

eureka:
  instance: eureka-dev.com
  client:
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka-dev.com:8001/eureka/
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: qx-config-eureka-client

eureka:
  instance: eureka-dev.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-dev.com:8001/eureka/
